###
### Dockerfile used for augmentation pipeline code
###
FROM tensorflow/tensorflow:latest-gpu
MAINTAINER Vincent Vanhoucke <vanhoucke@google.com>
RUN pip install scikit-learn scikit-image opencv-python==3.2.0.8
