###
### Dockerfile used for augmentation pipeline code
###
FROM tensorflow/tensorflow:1.15.2-gpu
MAINTAINER Vincent Vanhoucke <vanhoucke@google.com>
RUN pip install scipy==1.1.0 scikit-learn scikit-image opencv-python==3.2.0.8
